---
- hosts: devops
  user: gfg
  become: yes
  connection: ssh
  tasks:

    - name: Installation HTTPD
      action: yum name=httpd state=absent
    - name: Install Git
      action: yum name=git state=absent purge=yes
